#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BlueprintDebuggingInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "BlueprintLogLevel_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BlueprintDebuggingInterface.BlueprintDebuggingInterface_C
// 0x0000 (0x0000 - 0x0000)
class IBlueprintDebuggingInterface_C final
{
public:
	void GetBlueprintLogLevel(EBlueprintLogLevel* BlueprintLogLevel);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintDebuggingInterface_C">();
	}
	static class IBlueprintDebuggingInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBlueprintDebuggingInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBlueprintDebuggingInterface_C) == 0x000001, "Wrong alignment on IBlueprintDebuggingInterface_C");
static_assert(sizeof(IBlueprintDebuggingInterface_C) == 0x000001, "Wrong size on IBlueprintDebuggingInterface_C");

}

