#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_DynVariantRow_FocusTargetWidget

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_DynVariantRow_FocusTargetWidget.BPI_DynVariantRow_FocusTargetWidget_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_DynVariantRow_FocusTargetWidget_C final
{
public:
	void GetDesiredFocusTarget(class UWidget** FocusTarget) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_DynVariantRow_FocusTargetWidget_C">();
	}
	static class IBPI_DynVariantRow_FocusTargetWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_DynVariantRow_FocusTargetWidget_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_DynVariantRow_FocusTargetWidget_C) == 0x000001, "Wrong alignment on IBPI_DynVariantRow_FocusTargetWidget_C");
static_assert(sizeof(IBPI_DynVariantRow_FocusTargetWidget_C) == 0x000001, "Wrong size on IBPI_DynVariantRow_FocusTargetWidget_C");

}

