#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CentralPicnicNativeRuntime

#include "Basic.hpp"

#include "CentralPicnicNativeRuntime_classes.hpp"
#include "CentralPicnicNativeRuntime_parameters.hpp"


namespace SDK
{

// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.HandleMeshNetworkTypeSet
// (Final, Native, Private)
// Parameters:
// EMeshNetworkNodeType                    NodeType                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::HandleMeshNetworkTypeSet(EMeshNetworkNodeType NodeType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "HandleMeshNetworkTypeSet");

	Params::CentralPicnicMeshNetworkBridge_HandleMeshNetworkTypeSet Parms{};

	Parms.NodeType = NodeType;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.WaitForMeshNetwork
// (Final, Native, Protected)

void ACentralPicnicMeshNetworkBridge::WaitForMeshNetwork()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "WaitForMeshNetwork");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.BroadcastEvent_ChainsDamaged
// (Final, Native, Public, BlueprintCallable, Const)
// Parameters:
// const int64                             DamageDealt                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::BroadcastEvent_ChainsDamaged(const int64 DamageDealt) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "BroadcastEvent_ChainsDamaged");

	Params::CentralPicnicMeshNetworkBridge_BroadcastEvent_ChainsDamaged Parms{};

	Parms.DamageDealt = DamageDealt;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.BroadcastEvent_DamageModifierUpdated
// (Final, Native, Public, BlueprintCallable, Const)
// Parameters:
// const float                             NewValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::BroadcastEvent_DamageModifierUpdated(const float NewValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "BroadcastEvent_DamageModifierUpdated");

	Params::CentralPicnicMeshNetworkBridge_BroadcastEvent_DamageModifierUpdated Parms{};

	Parms.NewValue = NewValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.BroadcastEvent_DefaultHealthUpdated
// (Final, Native, Public, BlueprintCallable, Const)
// Parameters:
// const int64                             NewValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::BroadcastEvent_DefaultHealthUpdated(const int64 NewValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "BroadcastEvent_DefaultHealthUpdated");

	Params::CentralPicnicMeshNetworkBridge_BroadcastEvent_DefaultHealthUpdated Parms{};

	Parms.NewValue = NewValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.BroadcastEvent_HealthUpdated
// (Final, Native, Public, BlueprintCallable, Const)
// Parameters:
// const int64                             NewValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::BroadcastEvent_HealthUpdated(const int64 NewValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "BroadcastEvent_HealthUpdated");

	Params::CentralPicnicMeshNetworkBridge_BroadcastEvent_HealthUpdated Parms{};

	Parms.NewValue = NewValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.OnRep_CurrentHealth
// (Final, Native, Protected, BlueprintCallable, Const)
// Parameters:
// const int64                             OldValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::OnRep_CurrentHealth(const int64 OldValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "OnRep_CurrentHealth");

	Params::CentralPicnicMeshNetworkBridge_OnRep_CurrentHealth Parms{};

	Parms.OldValue = OldValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.OnRep_DamageModifier
// (Final, Native, Protected, BlueprintCallable, Const)
// Parameters:
// const float                             OldValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::OnRep_DamageModifier(const float OldValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "OnRep_DamageModifier");

	Params::CentralPicnicMeshNetworkBridge_OnRep_DamageModifier Parms{};

	Parms.OldValue = OldValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function CentralPicnicNativeRuntime.CentralPicnicMeshNetworkBridge.OnRep_DefaultHealth
// (Final, Native, Protected, BlueprintCallable, Const)
// Parameters:
// const int64                             OldValue                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ACentralPicnicMeshNetworkBridge::OnRep_DefaultHealth(const int64 OldValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CentralPicnicMeshNetworkBridge", "OnRep_DefaultHealth");

	Params::CentralPicnicMeshNetworkBridge_OnRep_DefaultHealth Parms{};

	Parms.OldValue = OldValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

