#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DelMarFrontend

#include "Basic.hpp"

#include "DelMarFrontend_classes.hpp"
#include "DelMarFrontend_parameters.hpp"


namespace SDK
{

// Function DelMarFrontend.DelMarFrontendCheatManager.DelMarMarkTutorialPlayed
// (Final, Exec, Native, Protected)

void UDelMarFrontendCheatManager::DelMarMarkTutorialPlayed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DelMarFrontendCheatManager", "DelMarMarkTutorialPlayed");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function DelMarFrontend.DelMarFrontendCheatManager.DelMarResetNux
// (Final, Exec, Native, Protected)

void UDelMarFrontendCheatManager::DelMarResetNux()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DelMarFrontendCheatManager", "DelMarResetNux");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function DelMarFrontend.DelMarFrontendRuntimeOptions.GetDelMarFrontendRuntimeOptions
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UDelMarFrontendRuntimeOptions*    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UDelMarFrontendRuntimeOptions* UDelMarFrontendRuntimeOptions::GetDelMarFrontendRuntimeOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("DelMarFrontendRuntimeOptions", "GetDelMarFrontendRuntimeOptions");

	Params::DelMarFrontendRuntimeOptions_GetDelMarFrontendRuntimeOptions Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

