#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EpicGamesAssets

#include "Basic.hpp"

#include "EpicGamesAssets_classes.hpp"
#include "EpicGamesAssets_parameters.hpp"


namespace SDK
{

// Function EpicGamesAssets.SpawnedParticleSystemReplication.OnRep_StartTime
// (Final, Native, Private)

void ASpawnedParticleSystemReplication::OnRep_StartTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpawnedParticleSystemReplication", "OnRep_StartTime");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function EpicGamesAssets.SpawnedParticleSystemReplication.OnRep_VFXAsset
// (Final, Native, Private)

void ASpawnedParticleSystemReplication::OnRep_VFXAsset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpawnedParticleSystemReplication", "OnRep_VFXAsset");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function EpicGamesAssets.SpawnedParticleSystemReplication.OnSystemFinished
// (Final, Native, Private)
// Parameters:
// class UNiagaraComponent*                FinishedComponent                                      (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASpawnedParticleSystemReplication::OnSystemFinished(class UNiagaraComponent* FinishedComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SpawnedParticleSystemReplication", "OnSystemFinished");

	Params::SpawnedParticleSystemReplication_OnSystemFinished Parms{};

	Parms.FinishedComponent = FinishedComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

