#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Execution_0

#include "Basic.hpp"

#include "Execution_0_classes.hpp"
#include "Execution_0_parameters.hpp"


namespace SDK
{

// Function Execution.Execution_execution_subscribable.$Block
// ()

void UExecution_execution_subscribable::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscribable", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscribable.$InitCDO
// ()

void UExecution_execution_subscribable::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscribable", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscribable.$InitInstance
// ()

void UExecution_execution_subscribable::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscribable", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscribable._L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribe_L_Ntuple_L_R_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct Execution_0::Ftuple_Ltuple_L_R_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R&__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UExecution_execution_subscription*RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UExecution_execution_subscription* UExecution_execution_subscribable::_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribe_L_Ntuple_L_R_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R(const struct Execution_0::Ftuple_Ltuple_L_R_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscribable", "_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribe_L_Ntuple_L_R_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R");

	Params::Execution_execution_subscribable__L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribe_L_Ntuple_L_R_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function Execution.Execution_execution_subscribable._L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribeWithTime_L_Nfloat_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct Execution_0::Ftuple_Lfloat_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R&__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UExecution_execution_subscription*RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UExecution_execution_subscription* UExecution_execution_subscribable::_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribeWithTime_L_Nfloat_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R(const struct Execution_0::Ftuple_Lfloat_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscribable", "_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribeWithTime_L_Nfloat_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R");

	Params::Execution_execution_subscribable__L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscribable_N_RSubscribeWithTime_L_Nfloat_Tvoid_M_N_QInterval_Nfloat_20_3d_20_2e_2e_2e_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function Execution.Execution_execution_subscription.$Block
// ()

void UExecution_execution_subscription::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscription.$InitCDO
// ()

void UExecution_execution_subscription::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscription.$InitInstance
// ()

void UExecution_execution_subscription::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Execution.Execution_execution_subscription._L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunAfter_L_Nexecution__subscription_R
// (Native, Public, BlueprintCallable)
// Parameters:
// class UExecution_execution_subscription*__verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void UExecution_execution_subscription::_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunAfter_L_Nexecution__subscription_R(class UExecution_execution_subscription* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunAfter_L_Nexecution__subscription_R");

	Params::Execution_execution_subscription__L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunAfter_L_Nexecution__subscription_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Execution.Execution_execution_subscription._L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunBefore_L_Nexecution__subscription_R
// (Native, Public, BlueprintCallable)
// Parameters:
// class UExecution_execution_subscription*__verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void UExecution_execution_subscription::_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunBefore_L_Nexecution__subscription_R(class UExecution_execution_subscription* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "_L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunBefore_L_Nexecution__subscription_R");

	Params::Execution_execution_subscription__L_2fUnrealEngine_2ecom_2fExecution_2fexecution__subscription_N_RRunBefore_L_Nexecution__subscription_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function Execution.Execution_execution_subscription._L_2fVerse_2eorg_2fVerse_2fcancelable_N_RCancel
// (Native, Public, BlueprintCallable)
// Parameters:
// const struct Execution_0::Ftuple_L_R&   __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UExecution_execution_subscription::_L_2fVerse_2eorg_2fVerse_2fcancelable_N_RCancel(const struct Execution_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Execution_execution_subscription", "_L_2fVerse_2eorg_2fVerse_2fcancelable_N_RCancel");

	Params::Execution_execution_subscription__L_2fVerse_2eorg_2fVerse_2fcancelable_N_RCancel Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

