#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_VoidRedemption_Rebel_CtrlRig

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass F_MED_VoidRedemption_Rebel_CtrlRig.F_MED_VoidRedemption_Rebel_CtrlRig_C
// 0x0008 (0x0A28 - 0x0A20)
class UF_MED_VoidRedemption_Rebel_CtrlRig_C final : public UControlRig
{
public:
	class FName                                   temp_bone_control_1;                               // 0x0A20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_VoidRedemption_Rebel_CtrlRig_C">();
	}
	static class UF_MED_VoidRedemption_Rebel_CtrlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_VoidRedemption_Rebel_CtrlRig_C>();
	}
};
static_assert(alignof(UF_MED_VoidRedemption_Rebel_CtrlRig_C) == 0x000008, "Wrong alignment on UF_MED_VoidRedemption_Rebel_CtrlRig_C");
static_assert(sizeof(UF_MED_VoidRedemption_Rebel_CtrlRig_C) == 0x000A28, "Wrong size on UF_MED_VoidRedemption_Rebel_CtrlRig_C");
static_assert(offsetof(UF_MED_VoidRedemption_Rebel_CtrlRig_C, temp_bone_control_1) == 0x000A20, "Member 'UF_MED_VoidRedemption_Rebel_CtrlRig_C::temp_bone_control_1' has a wrong offset!");

}

