#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_Elastic_ASN_3_AnimBP_PRIME

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_MED_Elastic_ASN_3_AnimBP_PRIME.F_MED_Elastic_ASN_3_AnimBP_PRIME_C
// 0x1230 (0x1950 - 0x0720)
class UF_MED_Elastic_ASN_3_AnimBP_PRIME_C final : public UCustomCharacterPartAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0720(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0728(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0730(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0738(0x0020)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh_1;                  // 0x0758(0x0150)(ContainsInstancedReference)
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x08A8(0x0150)(ContainsInstancedReference)
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x09F8(0x00F0)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x0AE8(0x0128)()
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0C10(0x0960)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x1570(0x0128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x1698(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x16B8(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x16D8(0x0128)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x1800(0x0128)()
	double                                        HeadUp;                                            // 0x1928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Body_Mesh;                                         // 0x1930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APlayerPawn_Athena_C*                   Pawn_Owner;                                        // 0x1938(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Head_MESH;                                         // 0x1940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintInitializeAnimation();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_F_MED_Elastic_ASN_3_AnimBP_PRIME(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_Elastic_ASN_3_AnimBP_PRIME_C">();
	}
	static class UF_MED_Elastic_ASN_3_AnimBP_PRIME_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_Elastic_ASN_3_AnimBP_PRIME_C>();
	}
};
static_assert(alignof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C) == 0x000010, "Wrong alignment on UF_MED_Elastic_ASN_3_AnimBP_PRIME_C");
static_assert(sizeof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C) == 0x001950, "Wrong size on UF_MED_Elastic_ASN_3_AnimBP_PRIME_C");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, UberGraphFrame) == 0x000720, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimBlueprintExtension_PropertyAccess) == 0x000728, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimBlueprintExtension_Base) == 0x000730, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_Root) == 0x000738, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_CopyPoseFromMesh_1) == 0x000758, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_CopyPoseFromMesh_1' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_CopyPoseFromMesh) == 0x0008A8, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_LayeredBoneBlend) == 0x0009F8, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_LayeredBoneBlend' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_ModifyBone_3) == 0x000AE8, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_RigidBody) == 0x000C10, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_RigidBody' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_ModifyBone_2) == 0x001570, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_LocalToComponentSpace) == 0x001698, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_ComponentToLocalSpace) == 0x0016B8, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_ModifyBone_1) == 0x0016D8, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, AnimGraphNode_ModifyBone) == 0x001800, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, HeadUp) == 0x001928, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::HeadUp' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, Body_Mesh) == 0x001930, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::Body_Mesh' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, Pawn_Owner) == 0x001938, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::Pawn_Owner' has a wrong offset!");
static_assert(offsetof(UF_MED_Elastic_ASN_3_AnimBP_PRIME_C, Head_MESH) == 0x001940, "Member 'UF_MED_Elastic_ASN_3_AnimBP_PRIME_C::Head_MESH' has a wrong offset!");

}

