#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass F_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig.F_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C
// 0x0008 (0x0A28 - 0x0A20)
class UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C final : public UControlRig
{
public:
	bool                                          RigidBody_Enabled;                                 // 0x0A20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C">();
	}
	static class UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C>();
	}
};
static_assert(alignof(UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C) == 0x000008, "Wrong alignment on UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C");
static_assert(sizeof(UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C) == 0x000A28, "Wrong size on UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C");
static_assert(offsetof(UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C, RigidBody_Enabled) == 0x000A20, "Member 'UF_MED_VoidRedemption_Rebel_FaceAcc_CtrlRig_C::RigidBody_Enabled' has a wrong offset!");

}

