#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InventoryRequestInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class InventoryRequestInterface.PersistenceInventoryRequestInterface
// 0x0000 (0x0000 - 0x0000)
class IPersistenceInventoryRequestInterface final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PersistenceInventoryRequestInterface">();
	}
	static class IPersistenceInventoryRequestInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPersistenceInventoryRequestInterface>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IPersistenceInventoryRequestInterface) == 0x000001, "Wrong alignment on IPersistenceInventoryRequestInterface");
static_assert(sizeof(IPersistenceInventoryRequestInterface) == 0x000001, "Wrong size on IPersistenceInventoryRequestInterface");

}

