#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemizationCoreUI

#include "Basic.hpp"

#include "ItemizationCoreUI_classes.hpp"
#include "ItemizationCoreUI_parameters.hpp"


namespace SDK
{

// Function ItemizationCoreUI.InventoryCollectionViewModel.InitializeViewModel
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UObject*                          InitializingObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryCollectionViewModel::InitializeViewModel(class UObject* InitializingObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryCollectionViewModel", "InitializeViewModel");

	Params::InventoryCollectionViewModel_InitializeViewModel Parms{};

	Parms.InitializingObject = InitializingObject;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryCollectionViewModel.UnbindInventoryCollection
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bUnusedParam                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryCollectionViewModel::UnbindInventoryCollection(const bool bUnusedParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryCollectionViewModel", "UnbindInventoryCollection");

	Params::InventoryCollectionViewModel_UnbindInventoryCollection Parms{};

	Parms.bUnusedParam = bUnusedParam;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.DropAll
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bUnused                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::DropAll(const bool bUnused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "DropAll");

	Params::InventoryItemEntryViewModel_DropAll Parms{};

	Parms.bUnused = bUnused;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.DropAmount
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const int64                             Amount                                                 (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::DropAmount(const int64 Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "DropAmount");

	Params::InventoryItemEntryViewModel_DropAmount Parms{};

	Parms.Amount = Amount;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.DropHalf
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bUnused                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::DropHalf(const bool bUnused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "DropHalf");

	Params::InventoryItemEntryViewModel_DropHalf Parms{};

	Parms.bUnused = bUnused;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.SetEquippableItemActive
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bActive                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::SetEquippableItemActive(const bool bActive)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "SetEquippableItemActive");

	Params::InventoryItemEntryViewModel_SetEquippableItemActive Parms{};

	Parms.bActive = bActive;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.SetItemSlotNumber
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const int32                             SlotNumber                                             (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::SetItemSlotNumber(const int32 SlotNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "SetItemSlotNumber");

	Params::InventoryItemEntryViewModel_SetItemSlotNumber Parms{};

	Parms.SlotNumber = SlotNumber;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.ToggleEquippableItemActive
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bUnused                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::ToggleEquippableItemActive(const bool bUnused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "ToggleEquippableItemActive");

	Params::InventoryItemEntryViewModel_ToggleEquippableItemActive Parms{};

	Parms.bUnused = bUnused;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.UpdateCanSwap
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class UInventoryItemEntryViewModel*SwapInventoryItemEntryViewModel                        (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::UpdateCanSwap(const class UInventoryItemEntryViewModel* SwapInventoryItemEntryViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "UpdateCanSwap");

	Params::InventoryItemEntryViewModel_UpdateCanSwap Parms{};

	Parms.SwapInventoryItemEntryViewModel = SwapInventoryItemEntryViewModel;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.UseItem
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bUnused                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UInventoryItemEntryViewModel::UseItem(const bool bUnused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "UseItem");

	Params::InventoryItemEntryViewModel_UseItem Parms{};

	Parms.bUnused = bUnused;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.CanItemBeMadeActive
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::CanItemBeMadeActive() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "CanItemBeMadeActive");

	Params::InventoryItemEntryViewModel_CanItemBeMadeActive Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.CanItemBeMadeInactive
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::CanItemBeMadeInactive() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "CanItemBeMadeInactive");

	Params::InventoryItemEntryViewModel_CanItemBeMadeInactive Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetEquipSlotInputAction
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UInputAction*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UInputAction* UInventoryItemEntryViewModel::GetEquipSlotInputAction() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetEquipSlotInputAction");

	Params::InventoryItemEntryViewModel_GetEquipSlotInputAction Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetInventoryID
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGuid                      ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FGuid UInventoryItemEntryViewModel::GetInventoryID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetInventoryID");

	Params::InventoryItemEntryViewModel_GetInventoryID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemAmount
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 UInventoryItemEntryViewModel::GetItemAmount() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemAmount");

	Params::InventoryItemEntryViewModel_GetItemAmount Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemDefinition
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UItemDefinitionBase*        ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UItemDefinitionBase* UInventoryItemEntryViewModel::GetItemDefinition() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemDefinition");

	Params::InventoryItemEntryViewModel_GetItemDefinition Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemDescription
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

class FText UInventoryItemEntryViewModel::GetItemDescription() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemDescription");

	Params::InventoryItemEntryViewModel_GetItemDescription Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemEntryID
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGuid                      ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FGuid UInventoryItemEntryViewModel::GetItemEntryID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemEntryID");

	Params::InventoryItemEntryViewModel_GetItemEntryID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemIcon
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UTexture2D*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture2D* UInventoryItemEntryViewModel::GetItemIcon() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemIcon");

	Params::InventoryItemEntryViewModel_GetItemIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemIconDisplayTextType
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EItemIconDisplayTextType                ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EItemIconDisplayTextType UInventoryItemEntryViewModel::GetItemIconDisplayTextType() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemIconDisplayTextType");

	Params::InventoryItemEntryViewModel_GetItemIconDisplayTextType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

class FText UInventoryItemEntryViewModel::GetItemName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemName");

	Params::InventoryItemEntryViewModel_GetItemName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemPrimaryAmmoCount
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 UInventoryItemEntryViewModel::GetItemPrimaryAmmoCount() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemPrimaryAmmoCount");

	Params::InventoryItemEntryViewModel_GetItemPrimaryAmmoCount Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemRarity
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UItemRarity*                ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UItemRarity* UInventoryItemEntryViewModel::GetItemRarity() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemRarity");

	Params::InventoryItemEntryViewModel_GetItemRarity Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemSlotNumber
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UInventoryItemEntryViewModel::GetItemSlotNumber() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemSlotNumber");

	Params::InventoryItemEntryViewModel_GetItemSlotNumber Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetItemType
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UItemType*                  ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UItemType* UInventoryItemEntryViewModel::GetItemType() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetItemType");

	Params::InventoryItemEntryViewModel_GetItemType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetSmallItemIcon
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UTexture2D*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture2D* UInventoryItemEntryViewModel::GetSmallItemIcon() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetSmallItemIcon");

	Params::InventoryItemEntryViewModel_GetSmallItemIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetSoftItemIcon
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TSoftObjectPtr<class UTexture2D>        ReturnValue                                            (Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

TSoftObjectPtr<class UTexture2D> UInventoryItemEntryViewModel::GetSoftItemIcon() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetSoftItemIcon");

	Params::InventoryItemEntryViewModel_GetSoftItemIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.GetSoftSmallItemIcon
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TSoftObjectPtr<class UTexture2D>        ReturnValue                                            (Parm, OutParm, ReturnParm, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

TSoftObjectPtr<class UTexture2D> UInventoryItemEntryViewModel::GetSoftSmallItemIcon() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "GetSoftSmallItemIcon");

	Params::InventoryItemEntryViewModel_GetSoftSmallItemIcon Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.IsEquipSlotInputBindingVisible
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::IsEquipSlotInputBindingVisible() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "IsEquipSlotInputBindingVisible");

	Params::InventoryItemEntryViewModel_IsEquipSlotInputBindingVisible Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.IsItemActive
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::IsItemActive() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "IsItemActive");

	Params::InventoryItemEntryViewModel_IsItemActive Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.IsItemEntryIDValid
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::IsItemEntryIDValid() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "IsItemEntryIDValid");

	Params::InventoryItemEntryViewModel_IsItemEntryIDValid Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.IsItemIconLoading
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::IsItemIconLoading() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "IsItemIconLoading");

	Params::InventoryItemEntryViewModel_IsItemIconLoading Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryItemEntryViewModel.IsSmallItemIconLoading
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UInventoryItemEntryViewModel::IsSmallItemIconLoading() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryItemEntryViewModel", "IsSmallItemIconLoading");

	Params::InventoryItemEntryViewModel_IsSmallItemIconLoading Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModel.GetInventoryDefinition
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class UInventoryDefinition*       ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class UInventoryDefinition* UInventoryViewModel::GetInventoryDefinition() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryViewModel", "GetInventoryDefinition");

	Params::InventoryViewModel_GetInventoryDefinition Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModel.GetInventoryDescription
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class FText                       ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const class FText UInventoryViewModel::GetInventoryDescription() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryViewModel", "GetInventoryDescription");

	Params::InventoryViewModel_GetInventoryDescription Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModel.GetInventoryName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class FText                       ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const class FText UInventoryViewModel::GetInventoryName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryViewModel", "GetInventoryName");

	Params::InventoryViewModel_GetInventoryName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModel.GetTotalSlots
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UInventoryViewModel::GetTotalSlots() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("InventoryViewModel", "GetTotalSlots");

	Params::InventoryViewModel_GetTotalSlots Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModelAllowedConversionFunctions.FindInventoryViewModel
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// const class UInventoryDefinition*       InventoryDefinition                                    (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<class UInventoryViewModel*>&InventoryViewModels                                    (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class UInventoryViewModel*              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UInventoryViewModel* UInventoryViewModelAllowedConversionFunctions::FindInventoryViewModel(const class UInventoryDefinition* InventoryDefinition, const TArray<class UInventoryViewModel*>& InventoryViewModels)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("InventoryViewModelAllowedConversionFunctions", "FindInventoryViewModel");

	Params::InventoryViewModelAllowedConversionFunctions_FindInventoryViewModel Parms{};

	Parms.InventoryDefinition = InventoryDefinition;
	Parms.InventoryViewModels = std::move(InventoryViewModels);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.InventoryViewModelAllowedConversionFunctions.GetInventoryItemEntryViewModels
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// const TArray<class UInventoryItemEntryViewModel*>&InventoryItemEntryViewModels                           (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
// const bool                              bIncludeEmptySlots                                     (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<class UInventoryItemEntryViewModel*>ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UInventoryItemEntryViewModel*> UInventoryViewModelAllowedConversionFunctions::GetInventoryItemEntryViewModels(const TArray<class UInventoryItemEntryViewModel*>& InventoryItemEntryViewModels, const bool bIncludeEmptySlots)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("InventoryViewModelAllowedConversionFunctions", "GetInventoryItemEntryViewModels");

	Params::InventoryViewModelAllowedConversionFunctions_GetInventoryItemEntryViewModels Parms{};

	Parms.InventoryItemEntryViewModels = std::move(InventoryItemEntryViewModels);
	Parms.bIncludeEmptySlots = bIncludeEmptySlots;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function ItemizationCoreUI.UniformGridEntryPanel.SetGridItems
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const TArray<class UObject*>&           GridItems                                              (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UUniformGridEntryPanel::SetGridItems(const TArray<class UObject*>& GridItems)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UniformGridEntryPanel", "SetGridItems");

	Params::UniformGridEntryPanel_SetGridItems Parms{};

	Parms.GridItems = std::move(GridItems);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function ItemizationCoreUI.UniformGridEntryPanel.SetSlotAlignment
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const EHorizontalAlignment              InSlotHorizontalAlignment                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const EVerticalAlignment                InSlotVerticalAlignment                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUniformGridEntryPanel::SetSlotAlignment(const EHorizontalAlignment InSlotHorizontalAlignment, const EVerticalAlignment InSlotVerticalAlignment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UniformGridEntryPanel", "SetSlotAlignment");

	Params::UniformGridEntryPanel_SetSlotAlignment Parms{};

	Parms.InSlotHorizontalAlignment = InSlotHorizontalAlignment;
	Parms.InSlotVerticalAlignment = InSlotVerticalAlignment;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

