#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoWorldManagement

#include "Basic.hpp"

#include "JunoWorldManagement_classes.hpp"
#include "JunoWorldManagement_parameters.hpp"


namespace SDK
{

// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_CreateWorld
// (Final, Net, NetReliable, NetRequest, Native, Event, Private, HasOutParams)
// Parameters:
// const struct FJsonObjectWrapper&        world_metadata                                         (ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_CreateWorld(const struct FJsonObjectWrapper& world_metadata, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_CreateWorld");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_CreateWorld Parms{};

	Parms.world_metadata = std::move(world_metadata);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_DeleteAllWorlds
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_DeleteAllWorlds(struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_DeleteAllWorlds");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_DeleteAllWorlds Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_DeleteWorld
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_DeleteWorld(const class FString& WorldId, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_DeleteWorld");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_DeleteWorld Parms{};

	Parms.WorldId = std::move(WorldId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_MarkWorldDeleted
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_MarkWorldDeleted(const class FString& WorldId, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_MarkWorldDeleted");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_MarkWorldDeleted Parms{};

	Parms.WorldId = std::move(WorldId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_SetWorldName
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Name_0                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_SetWorldName(const class FString& WorldId, const class FString& Name_0, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_SetWorldName");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_SetWorldName Parms{};

	Parms.WorldId = std::move(WorldId);
	Parms.Name_0 = std::move(Name_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_UpdateWorldLastAccessTime
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_UpdateWorldLastAccessTime(const class FString& WorldId, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_UpdateWorldLastAccessTime");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_UpdateWorldLastAccessTime Parms{};

	Parms.WorldId = std::move(WorldId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_UpdateWorldMetadata
// (Final, Net, NetReliable, NetRequest, Native, Event, Private, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FJsonObjectWrapper&        WorldMetadata                                          (ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FClientUrlContext*               Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_UpdateWorldMetadata(const class FString& WorldId, const struct FJsonObjectWrapper& WorldMetadata, struct FClientUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_UpdateWorldMetadata");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_UpdateWorldMetadata Parms{};

	Parms.WorldId = std::move(WorldId);
	Parms.WorldMetadata = std::move(WorldMetadata);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}


// Function JunoWorldManagement.JunoWorldMCPProto_Profile.ProtoJuno_UpdateWorldSysMetadata
// (Net, NetReliable, NetRequest, Native, Event, Public, HasOutParams)
// Parameters:
// const class FString&                    WorldId                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FJsonObjectWrapper&        SysMetadata                                            (ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
// struct FDedicatedServerUrlContext*      Context                                                (Parm, OutParm, RepSkip, NativeAccessSpecifierPublic)

void UJunoWorldMCPProto_Profile::ProtoJuno_UpdateWorldSysMetadata(const class FString& WorldId, const struct FJsonObjectWrapper& SysMetadata, struct FDedicatedServerUrlContext* Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoWorldMCPProto_Profile", "ProtoJuno_UpdateWorldSysMetadata");

	Params::JunoWorldMCPProto_Profile_ProtoJuno_UpdateWorldSysMetadata Parms{};

	Parms.WorldId = std::move(WorldId);
	Parms.SysMetadata = std::move(SysMetadata);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Context != nullptr)
		*Context = std::move(Parms.Context);
}

}

