#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoAIRuntime

#include "Basic.hpp"

#include "JunoAIRuntime_classes.hpp"
#include "JunoAIRuntime_parameters.hpp"


namespace SDK
{

// Function JunoAIRuntime.JunoAICampPawnComponent.ConvertAIRoleToDisplayText
// (Final, RequiredAPI, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTag&              AIRole                                                 (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FText                       ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const class FText UJunoAICampPawnComponent::ConvertAIRoleToDisplayText(const struct FGameplayTag& AIRole) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICampPawnComponent", "ConvertAIRoleToDisplayText");

	Params::JunoAICampPawnComponent_ConvertAIRoleToDisplayText Parms{};

	Parms.AIRole = std::move(AIRole);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function JunoAIRuntime.JunoAICampPawnComponent.GetAIRole
// (Final, RequiredAPI, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTag               ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FGameplayTag UJunoAICampPawnComponent::GetAIRole() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICampPawnComponent", "GetAIRole");

	Params::JunoAICampPawnComponent_GetAIRole Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function JunoAIRuntime.JunoAICampPawnComponent.GetAIRoleDisplayText
// (Final, RequiredAPI, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class FText                       ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const class FText UJunoAICampPawnComponent::GetAIRoleDisplayText() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICampPawnComponent", "GetAIRoleDisplayText");

	Params::JunoAICampPawnComponent_GetAIRoleDisplayText Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function JunoAIRuntime.JunoAICampPawnComponent.GetSoftRemovedReasons
// (Final, Native, Private, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTagContainer      ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const struct FGameplayTagContainer UJunoAICampPawnComponent::GetSoftRemovedReasons() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICampPawnComponent", "GetSoftRemovedReasons");

	Params::JunoAICampPawnComponent_GetSoftRemovedReasons Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function JunoAIRuntime.PlayspaceComponent_Root_JunoAIManagement.HandleFTUENPCSpawned
// (Final, Native, Private)
// Parameters:
// const class AActor*                     FTUENPC                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayspaceComponent_Root_JunoAIManagement::HandleFTUENPCSpawned(const class AActor* FTUENPC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PlayspaceComponent_Root_JunoAIManagement", "HandleFTUENPCSpawned");

	Params::PlayspaceComponent_Root_JunoAIManagement_HandleFTUENPCSpawned Parms{};

	Parms.FTUENPC = FTUENPC;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoAIRuntime.JunoAISafetyBubbleComponent.OnTimeOfDayPhaseChanged
// (Final, Native, Protected)
// Parameters:
// EFortDayPhase                           CurrentDayPhase                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EFortDayPhase                           PreviousDayPhase                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bAtCreation                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoAISafetyBubbleComponent::OnTimeOfDayPhaseChanged(EFortDayPhase CurrentDayPhase, EFortDayPhase PreviousDayPhase, bool bAtCreation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAISafetyBubbleComponent", "OnTimeOfDayPhaseChanged");

	Params::JunoAISafetyBubbleComponent_OnTimeOfDayPhaseChanged Parms{};

	Parms.CurrentDayPhase = CurrentDayPhase;
	Parms.PreviousDayPhase = PreviousDayPhase;
	Parms.bAtCreation = bAtCreation;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoAIRuntime.JunoAICheatManager.JunoEnableFriendlyCreatures
// (Final, BlueprintAuthorityOnly, Exec, Native, Private)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoAICheatManager::JunoEnableFriendlyCreatures(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICheatManager", "JunoEnableFriendlyCreatures");

	Params::JunoAICheatManager_JunoEnableFriendlyCreatures Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoAIRuntime.JunoAICheatManager.JunoEnableFriendlyNPCs
// (Final, BlueprintAuthorityOnly, Exec, Native, Private)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoAICheatManager::JunoEnableFriendlyNPCs(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICheatManager", "JunoEnableFriendlyNPCs");

	Params::JunoAICheatManager_JunoEnableFriendlyNPCs Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoAIRuntime.JunoAICheatManager.JunoEnableHostileCreatures
// (Final, BlueprintAuthorityOnly, Exec, Native, Private)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoAICheatManager::JunoEnableHostileCreatures(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoAICheatManager", "JunoEnableHostileCreatures");

	Params::JunoAICheatManager_JunoEnableHostileCreatures Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

