#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoMusicRuntime

#include "Basic.hpp"

#include "JunoMusicRuntime_classes.hpp"
#include "JunoMusicRuntime_parameters.hpp"


namespace SDK
{

// Function JunoMusicRuntime.ActiveJunoMusicPlayer.OnActiveMusicElementControllerFinishedPlaying
// (Final, Native, Public)

void UActiveJunoMusicPlayer::OnActiveMusicElementControllerFinishedPlaying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActiveJunoMusicPlayer", "OnActiveMusicElementControllerFinishedPlaying");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.ActiveJunoMusicPlayer.OnActiveMusicPlayerCooldownFinished
// (Final, Native, Public)

void UActiveJunoMusicPlayer::OnActiveMusicPlayerCooldownFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActiveJunoMusicPlayer", "OnActiveMusicPlayerCooldownFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.ActiveJunoMusicPlayer.OnDayNightPhaseChangeSignature
// (Final, Native, Public)
// Parameters:
// EFortDayPhase                           CurrentDayPhaseIn                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EFortDayPhase                           PreviousDayPhaseIn                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bAtCreationIn                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UActiveJunoMusicPlayer::OnDayNightPhaseChangeSignature(EFortDayPhase CurrentDayPhaseIn, EFortDayPhase PreviousDayPhaseIn, bool bAtCreationIn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActiveJunoMusicPlayer", "OnDayNightPhaseChangeSignature");

	Params::ActiveJunoMusicPlayer_OnDayNightPhaseChangeSignature Parms{};

	Parms.CurrentDayPhaseIn = CurrentDayPhaseIn;
	Parms.PreviousDayPhaseIn = PreviousDayPhaseIn;
	Parms.bAtCreationIn = bAtCreationIn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoActiveMusicElement_Base.OnFinishedPlaying
// (Native, Public)

void UJunoActiveMusicElement_Base::OnFinishedPlaying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoActiveMusicElement_Base", "OnFinishedPlaying");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicDataCollector.BP_OnRegistered
// (Event, Public, BlueprintEvent)
// Parameters:
// class UMetasoundParameterPack*          AggregatedData                                         (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicDataCollector::BP_OnRegistered(class UMetasoundParameterPack* AggregatedData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicDataCollector", "BP_OnRegistered");

	Params::JunoMusicDataCollector_BP_OnRegistered Parms{};

	Parms.AggregatedData = AggregatedData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function JunoMusicRuntime.JunoMusicDataCollector.BP_OnUnregistered
// (Event, Public, BlueprintEvent)

void UJunoMusicDataCollector::BP_OnUnregistered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicDataCollector", "BP_OnUnregistered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function JunoMusicRuntime.JunoMusicDataCollector.BP_OnUpdate
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UMetasoundParameterPack*          AggregatedData                                         (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicDataCollector::BP_OnUpdate(float DeltaSeconds, class UMetasoundParameterPack* AggregatedData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicDataCollector", "BP_OnUpdate");

	Params::JunoMusicDataCollector_BP_OnUpdate Parms{};

	Parms.DeltaSeconds = DeltaSeconds;
	Parms.AggregatedData = AggregatedData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function JunoMusicRuntime.JunoMusicDataCollector_Combat.SetThreatLevelMultiplier
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// const float                             InThreatLevelMultiplier                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicDataCollector_Combat::SetThreatLevelMultiplier(const float InThreatLevelMultiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicDataCollector_Combat", "SetThreatLevelMultiplier");

	Params::JunoMusicDataCollector_Combat_SetThreatLevelMultiplier Parms{};

	Parms.InThreatLevelMultiplier = InThreatLevelMultiplier;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.AddJunoMusicPlaylist
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UJunoMusicPlaylistDataAsset*      JunoMusicPlaylist                                      (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::AddJunoMusicPlaylist(class UJunoMusicPlaylistDataAsset* JunoMusicPlaylist)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "AddJunoMusicPlaylist");

	Params::JunoMusicManager_AddJunoMusicPlaylist Parms{};

	Parms.JunoMusicPlaylist = JunoMusicPlaylist;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.RemoveJunoMusicPlaylist
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UJunoMusicPlaylistDataAsset*      JunoMusicPlaylist                                      (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::RemoveJunoMusicPlaylist(class UJunoMusicPlaylistDataAsset* JunoMusicPlaylist)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "RemoveJunoMusicPlaylist");

	Params::JunoMusicManager_RemoveJunoMusicPlaylist Parms{};

	Parms.JunoMusicPlaylist = JunoMusicPlaylist;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.SetActiveJunoMusicManagerData
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FActiveJunoMusicManagerData&ActiveJunoMusicManagerDataIn                           (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void UJunoMusicManager::SetActiveJunoMusicManagerData(const struct FActiveJunoMusicManagerData& ActiveJunoMusicManagerDataIn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "SetActiveJunoMusicManagerData");

	Params::JunoMusicManager_SetActiveJunoMusicManagerData Parms{};

	Parms.ActiveJunoMusicManagerDataIn = std::move(ActiveJunoMusicManagerDataIn);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.SetSuspendActiveMusicPlayback
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bSuspendPlayback                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bStopCurrentlyPlayingMusic                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::SetSuspendActiveMusicPlayback(bool bSuspendPlayback, bool bStopCurrentlyPlayingMusic)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "SetSuspendActiveMusicPlayback");

	Params::JunoMusicManager_SetSuspendActiveMusicPlayback Parms{};

	Parms.bSuspendPlayback = bSuspendPlayback;
	Parms.bStopCurrentlyPlayingMusic = bStopCurrentlyPlayingMusic;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.SetSuspendWorldActiveMusicPlayback
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           World                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSuspendPlayback                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bStopCurrentlyPlayingMusic                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::SetSuspendWorldActiveMusicPlayback(class UWorld* World, bool bSuspendPlayback, bool bStopCurrentlyPlayingMusic)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "SetSuspendWorldActiveMusicPlayback");

	Params::JunoMusicManager_SetSuspendWorldActiveMusicPlayback Parms{};

	Parms.World = World;
	Parms.bSuspendPlayback = bSuspendPlayback;
	Parms.bStopCurrentlyPlayingMusic = bStopCurrentlyPlayingMusic;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.StartWorldMusicSystem
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           World                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::StartWorldMusicSystem(class UWorld* World)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "StartWorldMusicSystem");

	Params::JunoMusicManager_StartWorldMusicSystem Parms{};

	Parms.World = World;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.StopWorldMusicSystem
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           World                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoMusicManager::StopWorldMusicSystem(class UWorld* World)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "StopWorldMusicSystem");

	Params::JunoMusicManager_StopWorldMusicSystem Parms{};

	Parms.World = World;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function JunoMusicRuntime.JunoMusicManager.GetCollectedBool
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ParameterName                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESetParamResult*                        Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UJunoMusicManager::GetCollectedBool(class UObject* WorldContextObject, class FName ParameterName, ESetParamResult* Result) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "GetCollectedBool");

	Params::JunoMusicManager_GetCollectedBool Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ParameterName = ParameterName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}


// Function JunoMusicRuntime.JunoMusicManager.GetCollectedFloat
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ParameterName                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESetParamResult*                        Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UJunoMusicManager::GetCollectedFloat(class UObject* WorldContextObject, class FName ParameterName, ESetParamResult* Result) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "GetCollectedFloat");

	Params::JunoMusicManager_GetCollectedFloat Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ParameterName = ParameterName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}


// Function JunoMusicRuntime.JunoMusicManager.GetCollectedInt
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ParameterName                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESetParamResult*                        Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UJunoMusicManager::GetCollectedInt(class UObject* WorldContextObject, class FName ParameterName, ESetParamResult* Result) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "GetCollectedInt");

	Params::JunoMusicManager_GetCollectedInt Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ParameterName = ParameterName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}


// Function JunoMusicRuntime.JunoMusicManager.GetCollectedString
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ParameterName                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ESetParamResult*                        Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UJunoMusicManager::GetCollectedString(class UObject* WorldContextObject, class FName ParameterName, ESetParamResult* Result) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicManager", "GetCollectedString");

	Params::JunoMusicManager_GetCollectedString Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.ParameterName = ParameterName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}


// Function JunoMusicRuntime.JunoMusicPlaybackCondition.BP_OnRegistered
// (Event, Public, BlueprintEvent)

void UJunoMusicPlaybackCondition::BP_OnRegistered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicPlaybackCondition", "BP_OnRegistered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function JunoMusicRuntime.JunoMusicPlaybackCondition.BP_OnUnregistered
// (Event, Public, BlueprintEvent)

void UJunoMusicPlaybackCondition::BP_OnUnregistered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicPlaybackCondition", "BP_OnUnregistered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function JunoMusicRuntime.JunoMusicPlaybackCondition.BP_ShouldPlay
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UJunoMusicPlaybackCondition::BP_ShouldPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("JunoMusicPlaybackCondition", "BP_ShouldPlay");

	Params::JunoMusicPlaybackCondition_BP_ShouldPlay Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

