#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoFrontendUI

#include "Basic.hpp"


namespace SDK
{

// Enum JunoFrontendUI.EOptionalJunoFrontendExperienceFlowSteps
// NumValues: 0x0002
enum class EOptionalJunoFrontendExperienceFlowSteps : uint8
{
	TryShowCinematicTrailer                  = 0,
	EOptionalJunoFrontendExperienceFlowSteps_MAX = 1,
};

}

