#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LinedNotebookTabAudio

#include "Basic.hpp"

#include "LinedNotebookTabAudio_classes.hpp"
#include "LinedNotebookTabAudio_parameters.hpp"


namespace SDK
{

// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.ExecuteUbergraph_LinedNotebookTabAudio
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULinedNotebookTabAudio_C::ExecuteUbergraph_LinedNotebookTabAudio(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "ExecuteUbergraph_LinedNotebookTabAudio");

	Params::LinedNotebookTabAudio_C_ExecuteUbergraph_LinedNotebookTabAudio Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.OnTabDestroyed
// (Event, Public, BlueprintEvent)

void ULinedNotebookTabAudio_C::OnTabDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "OnTabDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.OnTabEntered
// (Event, Public, BlueprintEvent)

void ULinedNotebookTabAudio_C::OnTabEntered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "OnTabEntered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.OnTabExited
// (Event, Public, BlueprintEvent)

void ULinedNotebookTabAudio_C::OnTabExited()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "OnTabExited");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.OnTabInitialized
// (Event, Public, BlueprintEvent)

void ULinedNotebookTabAudio_C::OnTabInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "OnTabInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LinedNotebookTabAudio.LinedNotebookTabAudio_C.StartNormalLobbyMusic
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ULinedNotebookTabAudio_C::StartNormalLobbyMusic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LinedNotebookTabAudio_C", "StartNormalLobbyMusic");

	UObject::ProcessEvent(Func, nullptr);
}

}

