#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PhaseCommits

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class PhaseCommits.PhaseCommitFlow_Coordinator
// 0x0000 (0x0000 - 0x0000)
class IPhaseCommitFlow_Coordinator final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PhaseCommitFlow_Coordinator">();
	}
	static class IPhaseCommitFlow_Coordinator* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPhaseCommitFlow_Coordinator>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IPhaseCommitFlow_Coordinator) == 0x000001, "Wrong alignment on IPhaseCommitFlow_Coordinator");
static_assert(sizeof(IPhaseCommitFlow_Coordinator) == 0x000001, "Wrong size on IPhaseCommitFlow_Coordinator");

// Class PhaseCommits.PhaseCommitFlow_Participant
// 0x0000 (0x0000 - 0x0000)
class IPhaseCommitFlow_Participant final
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PhaseCommitFlow_Participant">();
	}
	static class IPhaseCommitFlow_Participant* GetDefaultObj()
	{
		return GetDefaultObjImpl<IPhaseCommitFlow_Participant>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IPhaseCommitFlow_Participant) == 0x000001, "Wrong alignment on IPhaseCommitFlow_Participant");
static_assert(sizeof(IPhaseCommitFlow_Participant) == 0x000001, "Wrong size on IPhaseCommitFlow_Participant");

}

