#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PilgrimCoreUI

#include "Basic.hpp"

#include "PilgrimCoreUI_classes.hpp"
#include "PilgrimCoreUI_parameters.hpp"


namespace SDK
{

// Function PilgrimCoreUI.PilgrimPlayerInfoWidgetBase.HookUpVoiceIcon
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UFortVoiceChatStatusIcon*         Icon                                                   (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortPlayerStateAthena*           Player                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPilgrimPlayerInfoWidgetBase::HookUpVoiceIcon(class UFortVoiceChatStatusIcon* Icon, class AFortPlayerStateAthena* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPlayerInfoWidgetBase", "HookUpVoiceIcon");

	Params::PilgrimPlayerInfoWidgetBase_HookUpVoiceIcon Parms{};

	Parms.Icon = Icon;
	Parms.Player = Player;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PilgrimCoreUI.PilgrimPostGameProgressWidget.GetMatchXP
// (Final, Native, Private, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPilgrimPostGameProgressWidget::GetMatchXP() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPostGameProgressWidget", "GetMatchXP");

	Params::PilgrimPostGameProgressWidget_GetMatchXP Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PilgrimCoreUI.PilgrimPostGameProgressWidget.GetTotalXP
// (Final, Native, Private, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPilgrimPostGameProgressWidget::GetTotalXP() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPostGameProgressWidget", "GetTotalXP");

	Params::PilgrimPostGameProgressWidget_GetTotalXP Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PilgrimCoreUI.PilgrimPresetSelector.OnPresetSelected
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   SelectedNumLanes                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   SelectedPresetIndex                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPilgrimPresetSelector::OnPresetSelected(int32 SelectedNumLanes, int32 SelectedPresetIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPresetSelector", "OnPresetSelected");

	Params::PilgrimPresetSelector_OnPresetSelected Parms{};

	Parms.SelectedNumLanes = SelectedNumLanes;
	Parms.SelectedPresetIndex = SelectedPresetIndex;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PilgrimCoreUI.PilgrimPresetSelector.OnPresetSelectionCancelled
// (Final, Native, Public, BlueprintCallable)

void UPilgrimPresetSelector::OnPresetSelectionCancelled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPresetSelector", "OnPresetSelectionCancelled");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PilgrimCoreUI.PilgrimPresetSelector.OnPresetSelectionRequested
// (Event, Protected, BlueprintEvent)
// Parameters:
// class APlayerController*                Player                                                 (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPilgrimPresetSelector::OnPresetSelectionRequested(class APlayerController* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPresetSelector", "OnPresetSelectionRequested");

	Params::PilgrimPresetSelector_OnPresetSelectionRequested Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PilgrimCoreUI.PilgrimPresetSwitcher.GetSelectedItems
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32*                                  OutSelectedLaneNum                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  OutSelectedIndex                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPilgrimPresetSwitcher::GetSelectedItems(int32* OutSelectedLaneNum, int32* OutSelectedIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPresetSwitcher", "GetSelectedItems");

	Params::PilgrimPresetSwitcher_GetSelectedItems Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutSelectedLaneNum != nullptr)
		*OutSelectedLaneNum = Parms.OutSelectedLaneNum;

	if (OutSelectedIndex != nullptr)
		*OutSelectedIndex = Parms.OutSelectedIndex;
}


// Function PilgrimCoreUI.PilgrimPresetSwitcher.InitializeForLanes
// (Final, Native, Private, HasOutParams, BlueprintCallable)
// Parameters:
// int32                                   NewNumLanes                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<class UFortInputMappingContext*>&InputMappingContexts                                   (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UPilgrimPresetSwitcher::InitializeForLanes(int32 NewNumLanes, const TArray<class UFortInputMappingContext*>& InputMappingContexts)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimPresetSwitcher", "InitializeForLanes");

	Params::PilgrimPresetSwitcher_InitializeForLanes Parms{};

	Parms.NewNumLanes = NewNumLanes;
	Parms.InputMappingContexts = std::move(InputMappingContexts);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PilgrimCoreUI.PilgrimSongFilterVM.Initialize
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class APlayerController*                InOwningController                                     (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPilgrimSongFilterVM::Initialize(class APlayerController* InOwningController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PilgrimSongFilterVM", "Initialize");

	Params::PilgrimSongFilterVM_Initialize Parms{};

	Parms.InOwningController = InOwningController;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

