#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SilkWalkerRuntime

#include "Basic.hpp"

#include "SilkWalkerRuntime_classes.hpp"
#include "SilkWalkerRuntime_parameters.hpp"


namespace SDK
{

// Function SilkWalkerRuntime.FortSilkwalkerComponent_Telemetry.OnGiftThrown
// (Final, Native, Private, BlueprintCallable)
// Parameters:
// const class AFortPawn*                  TargetPawn                                             (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const bool                              bGood                                                  (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortSilkwalkerComponent_Telemetry::OnGiftThrown(const class AFortPawn* TargetPawn, const bool bGood)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortSilkwalkerComponent_Telemetry", "OnGiftThrown");

	Params::FortSilkwalkerComponent_Telemetry_OnGiftThrown Parms{};

	Parms.TargetPawn = TargetPawn;
	Parms.bGood = bGood;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

