#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_ItemCard_Locker

#include "Basic.hpp"

#include "WBP_UIKit_ItemCard_Locker_classes.hpp"
#include "WBP_UIKit_ItemCard_Locker_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Apply to All
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::Apply_to_All()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Apply to All");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_0_OnContextMenuOpened__DelegateSignature
// (BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_0_OnContextMenuOpened__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_0_OnContextMenuOpened__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_1_OnContextMenuClosed__DelegateSignature
// (BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_1_OnContextMenuClosed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BndEvt__WBP_UIKit_ItemCard_Locker_ContextMenu_K2Node_ComponentBoundEvent_1_OnContextMenuClosed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnClicked
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnDeselected
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnDeselected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnDeselected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnDoubleClicked
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnDoubleClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnDoubleClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnHoldTriggered
// (BlueprintCosmetic, Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        CurrentInputType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_UIKit_ItemCard_Locker_C::BP_OnHoldTriggered(ECommonInputType CurrentInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnHoldTriggered");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnHoldTriggered Parms{};

	Parms.CurrentInputType = CurrentInputType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnInputMethodChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ECommonInputType                        CurrentInputType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnInputMethodChanged(ECommonInputType CurrentInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnInputMethodChanged");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnInputMethodChanged Parms{};

	Parms.CurrentInputType = CurrentInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnItemExpansionChanged");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnItemSelectionChanged");

	Params::WBP_UIKit_ItemCard_Locker_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnSelected
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Can Display Context Menu
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Value                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::Can_Display_Context_Menu(bool* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Can Display Context Menu");

	Params::WBP_UIKit_ItemCard_Locker_C_Can_Display_Context_Menu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Value != nullptr)
		*Value = Parms.Value;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.CloseContextMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::CloseContextMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "CloseContextMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.CompareLockerCategoryIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsApplytoAllInfoAvailable                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::CompareLockerCategoryIndex(bool* IsApplytoAllInfoAvailable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "CompareLockerCategoryIndex");

	Params::WBP_UIKit_ItemCard_Locker_C_CompareLockerCategoryIndex Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsApplytoAllInfoAvailable != nullptr)
		*IsApplytoAllInfoAvailable = Parms.IsApplytoAllInfoAvailable;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.EditStyles
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::EditStyles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "EditStyles");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Event On Archive Item
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::Event_On_Archive_Item()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Event On Archive Item");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Event On Favorite Item
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::Event_On_Favorite_Item()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Event On Favorite Item");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.ExecuteUbergraph_WBP_UIKit_ItemCard_Locker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::ExecuteUbergraph_WBP_UIKit_ItemCard_Locker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "ExecuteUbergraph_WBP_UIKit_ItemCard_Locker");

	Params::WBP_UIKit_ItemCard_Locker_C_ExecuteUbergraph_WBP_UIKit_ItemCard_Locker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.GetInitialArchiveState
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText*                            Result                                                 (Parm, OutParm)

void UWBP_UIKit_ItemCard_Locker_C::GetInitialArchiveState(class FText* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "GetInitialArchiveState");

	Params::WBP_UIKit_ItemCard_Locker_C_GetInitialArchiveState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = std::move(Parms.Result);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.GetInitialFavoriteState
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText*                            Result                                                 (Parm, OutParm)

void UWBP_UIKit_ItemCard_Locker_C::GetInitialFavoriteState(class FText* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "GetInitialFavoriteState");

	Params::WBP_UIKit_ItemCard_Locker_C_GetInitialFavoriteState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = std::move(Parms.Result);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnHold
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::OnHold()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnHold");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnListItemObjectSet");

	Params::WBP_UIKit_ItemCard_Locker_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnMouseButtonDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_UIKit_ItemCard_Locker_C::OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnMouseButtonDown");

	Params::WBP_UIKit_ItemCard_Locker_C_OnMouseButtonDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnOperationCompleted_2D0ECFBF4D017B0203E8508736C20384
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::OnOperationCompleted_2D0ECFBF4D017B0203E8508736C20384(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnOperationCompleted_2D0ECFBF4D017B0203E8508736C20384");

	Params::WBP_UIKit_ItemCard_Locker_C_OnOperationCompleted_2D0ECFBF4D017B0203E8508736C20384 Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.OnOperationCompleted_5A8AD2704B8B176D35386498F38A6122
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Success                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::OnOperationCompleted_5A8AD2704B8B176D35386498F38A6122(bool Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "OnOperationCompleted_5A8AD2704B8B176D35386498F38A6122");

	Params::WBP_UIKit_ItemCard_Locker_C_OnOperationCompleted_5A8AD2704B8B176D35386498F38A6122 Parms{};

	Parms.Success = Success;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "PreConstruct");

	Params::WBP_UIKit_ItemCard_Locker_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Set Is New
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsNew                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::Set_Is_New(bool IsNew)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Set Is New");

	Params::WBP_UIKit_ItemCard_Locker_C_Set_Is_New Parms{};

	Parms.IsNew = IsNew;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetArchiveState
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::SetArchiveState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetArchiveState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetContextMenuActionContext
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void()>&                ArchiveItemInInteractionDelegate                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const TDelegate<void()>&                FavoriteItemInInteractionDelegate                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const TDelegate<void()>&                ApplyToAllInInteractionDelegate                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const TDelegate<void()>&                EditStylesInInteractionDelegate                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetContextMenuActionContext(const TDelegate<void()>& ArchiveItemInInteractionDelegate, const TDelegate<void()>& FavoriteItemInInteractionDelegate, const TDelegate<void()>& ApplyToAllInInteractionDelegate, const TDelegate<void()>& EditStylesInInteractionDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetContextMenuActionContext");

	Params::WBP_UIKit_ItemCard_Locker_C_SetContextMenuActionContext Parms{};

	Parms.ArchiveItemInInteractionDelegate = ArchiveItemInInteractionDelegate;
	Parms.FavoriteItemInInteractionDelegate = FavoriteItemInInteractionDelegate;
	Parms.ApplyToAllInInteractionDelegate = ApplyToAllInInteractionDelegate;
	Parms.EditStylesInInteractionDelegate = EditStylesInInteractionDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetContextMenuPrimaryPreviewActions
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      PreviewActionName                                      (BlueprintVisible, BlueprintReadOnly, Parm)
// const TDelegate<void()>&                PreviewActionInInteractionDelegate                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetContextMenuPrimaryPreviewActions(const class FText& PreviewActionName, const TDelegate<void()>& PreviewActionInInteractionDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetContextMenuPrimaryPreviewActions");

	Params::WBP_UIKit_ItemCard_Locker_C_SetContextMenuPrimaryPreviewActions Parms{};

	Parms.PreviewActionName = std::move(PreviewActionName);
	Parms.PreviewActionInInteractionDelegate = PreviewActionInInteractionDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetContextMenuSecondaryPreviewActions
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      PreviewActionName                                      (BlueprintVisible, BlueprintReadOnly, Parm)
// const TDelegate<void()>&                PreviewActionInInteractionDelegate                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetContextMenuSecondaryPreviewActions(const class FText& PreviewActionName, const TDelegate<void()>& PreviewActionInInteractionDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetContextMenuSecondaryPreviewActions");

	Params::WBP_UIKit_ItemCard_Locker_C_SetContextMenuSecondaryPreviewActions Parms{};

	Parms.PreviewActionName = std::move(PreviewActionName);
	Parms.PreviewActionInInteractionDelegate = PreviewActionInInteractionDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetFavoriteState
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::SetFavoriteState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetFavoriteState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetFIVMItemAndSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemVM**                     Selected_Item                                          (Parm, OutParm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// int32*                                  Slot_Index                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetFIVMItemAndSlot(class UFortItemVM** Selected_Item, int32* Slot_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetFIVMItemAndSlot");

	Params::WBP_UIKit_ItemCard_Locker_C_SetFIVMItemAndSlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Selected_Item != nullptr)
		*Selected_Item = Parms.Selected_Item;

	if (Slot_Index != nullptr)
		*Slot_Index = Parms.Slot_Index;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.SetFortItemVM
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItemVM*                      ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::SetFortItemVM(class UFortItemVM* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "SetFortItemVM");

	Params::WBP_UIKit_ItemCard_Locker_C_SetFortItemVM Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.ToggleContextMenuIfSelected
// (BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_ItemCard_Locker_C::ToggleContextMenuIfSelected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "ToggleContextMenuIfSelected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Update Equipped Index
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Equipped_Index                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::Update_Equipped_Index(int32 Equipped_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Update Equipped Index");

	Params::WBP_UIKit_ItemCard_Locker_C_Update_Equipped_Index Parms{};

	Parms.Equipped_Index = Equipped_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.__019ca762-48ee-2a79-1b9f-5f9ab03f5146_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::__019ca762_48ee_2a79_1b9f_5f9ab03f5146_SourceToDest(bool* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "__019ca762-48ee-2a79-1b9f-5f9ab03f5146_SourceToDest");

	Params::WBP_UIKit_ItemCard_Locker_C___019ca762_48ee_2a79_1b9f_5f9ab03f5146_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function WBP_UIKit_ItemCard_Locker.WBP_UIKit_ItemCard_Locker_C.Is Item Equipped
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UFortItem*                        Category_Item                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UFortItem*                        Item_VM                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   NewParam                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_ItemCard_Locker_C::Is_Item_Equipped(class UFortItem* Category_Item, class UFortItem* Item_VM, bool* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UIKit_ItemCard_Locker_C", "Is Item Equipped");

	Params::WBP_UIKit_ItemCard_Locker_C_Is_Item_Equipped Parms{};

	Parms.Category_Item = Category_Item;
	Parms.Item_VM = Item_VM;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}

}

