#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CategoriesTabs

#include "Basic.hpp"

#include "WBP_CategoriesTabs_classes.hpp"
#include "WBP_CategoriesTabs_parameters.hpp"


namespace SDK
{

// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.ChangeNamesVisibility
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::ChangeNamesVisibility(bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "ChangeNamesVisibility");

	Params::WBP_CategoriesTabs_C_ChangeNamesVisibility Parms{};

	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CategoriesTabs_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.Event On Input Method Changed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::Event_On_Input_Method_Changed(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "Event On Input Method Changed");

	Params::WBP_CategoriesTabs_C_Event_On_Input_Method_Changed Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.ExecuteUbergraph_WBP_CategoriesTabs
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::ExecuteUbergraph_WBP_CategoriesTabs(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "ExecuteUbergraph_WBP_CategoriesTabs");

	Params::WBP_CategoriesTabs_C_ExecuteUbergraph_WBP_CategoriesTabs Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.HandleTabCreation
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             TabNameID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCommonButtonBase*                TabButton                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::HandleTabCreation(class FName TabNameID, class UCommonButtonBase* TabButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "HandleTabCreation");

	Params::WBP_CategoriesTabs_C_HandleTabCreation Parms{};

	Parms.TabNameID = TabNameID;
	Parms.TabButton = TabButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.HasHoveredItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsHovering                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::HasHoveredItem(bool* IsHovering)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "HasHoveredItem");

	Params::WBP_CategoriesTabs_C_HasHoveredItem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsHovering != nullptr)
		*IsHovering = Parms.IsHovering;
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_CategoriesTabs_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "OnMouseEnter");

	Params::WBP_CategoriesTabs_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_CategoriesTabs_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "OnMouseLeave");

	Params::WBP_CategoriesTabs_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.PopulateTabs
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UFortLockerCategoryGroupVM*>&Categories_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_CategoriesTabs_C::PopulateTabs(TArray<class UFortLockerCategoryGroupVM*>& Categories_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "PopulateTabs");

	Params::WBP_CategoriesTabs_C_PopulateTabs Parms{};

	Parms.Categories_0 = std::move(Categories_0);

	UObject::ProcessEvent(Func, &Parms);

	Categories_0 = std::move(Parms.Categories_0);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "PreConstruct");

	Params::WBP_CategoriesTabs_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.Select Tab
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::Select_Tab(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "Select Tab");

	Params::WBP_CategoriesTabs_C_Select_Tab Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CategoriesTabs.WBP_CategoriesTabs_C.SetInteractionEnabled
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CategoriesTabs_C::SetInteractionEnabled(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CategoriesTabs_C", "SetInteractionEnabled");

	Params::WBP_CategoriesTabs_C_SetInteractionEnabled Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}

}

