#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace VerseSimulationMetadata_0 { class USimulation; }

namespace F_MED_Jiyoon_Head_UnderChin_Transform_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace WBP_BattlePassDynamicIcon_0 { class UWBP_BattlePassDynamicIcon_C; }

namespace F_MED_VoidRedemption_Rebel_FaceAcc_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TextStyle_BurbankSmall_S_White_0 { class UTextStyle_BurbankSmall_S_White_C; }

namespace GoldenGuard_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace Mechanical_Engineer_Female_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace MetalScout_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace GenericPetLayer_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace TextStyle_BurbankSmall_S_White { class UTextStyle_BurbankSmall_S_White_C; }

namespace Player_RigidBodyPBA_AnimBP_Template { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Jiyoon_Head_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace WBP_BattlePassDynamicIcon { class UWBP_BattlePassDynamicIcon_C; }

namespace F_MED_Ramirez_Fallback_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace VerseMovement_0 { class U_SolarisSignatureFunctionOuter; }

namespace F_MED_Prime_Skeleton_AnimBlueprint { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_Elastic_ASN_3_AnimBP_PRIME { struct FAnimBlueprintGeneratedConstantData; }

namespace VerseParameterCollections_0 { class U_SolarisSignatureFunctionOuter; }

namespace M_MED_Patches_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace F_MED_VoidRedemption_Rebel_Head_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace EntityTestSuite { struct Ftuple_L_R; }

namespace VerseNative_0 { class U_Root; }

namespace ButtonStyle_Empty_0 { class UButtonStyle_Empty_C; }

namespace EmberRae_Axe_L_AnimBP_Post { struct FAnimBlueprintGeneratedConstantData; }

namespace Player_PropertiesDebug_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace Blueprint_Paper_VIM { struct FAnimBlueprintGeneratedConstantData; }

namespace EmberRae_Axe_R_AnimBP_Post { struct FAnimBlueprintGeneratedConstantData; }

namespace LoudPhoenix_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace NitroFlow_Axe_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace ButtonStyle_Empty { class UButtonStyle_Empty_C; }

namespace Fringe_Plank_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace GenericPetLayer_Radish_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace M_MED_HighTower_Radish_Pet_PostProcess_AnimBP { struct FAnimBlueprintGeneratedConstantData; }


namespace CompanionAI_0
{
	struct Ftuple_Ltarget__info_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lgameplay__ability__asset_M_QTarget_N_Qagent_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lgame__action__instigator_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace Player_DBNO_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Execution_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltuple_L_R_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R;
}

namespace B_MasterPetAnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace SlidingLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseColors
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lint_Mint_Mint_R;
}

namespace SpaceFeline_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_M_Avg_Player_AnimBlueprint
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseAssets_0
{
	class U_SolarisSignatureFunctionOuter;
	class UAssets;
	struct Ftuple_L_R;
	struct Ftuple_Lany_M_Kchar_R;
}

namespace HighTower_Tapas_Axe_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseFortniteGameplayAbilities_0
{
	struct Ftuple_Lgameplay__ability__asset_M_QTarget_N_Qagent_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace Chameleon_PostProcess_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VGameplayRst_0
{
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lcomponent_Many_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mlogic_R;
	struct Ftuple_Lvector3_M_Kchar_R;
}

namespace VerseConcurrency
{
	class U_Root;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseBasicGameplay
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_Kchar_R;
}

namespace VerseEngine_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lcomponent_Many_R;
}

namespace Player_ProceduralAdjustments_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace JackalVehicle_Hoverboard_Base_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseNPC_0
{
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfort__inventory__item__asset_Mint_R;
	struct Ftuple_Lguard__alert__level_Mdamage__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Mhearing__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Msight__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Mtouch__perception__settings_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
}

namespace Player_TacticalState_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseUI_0
{
	class UUI;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
}

namespace RidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseWorldPartition_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Grandma_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Burt_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace BoarRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_DBNOCarried_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_InAir_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseCreature_0
{
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace MenuScreen_Athena
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_LowerBodyJog_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VersePlayspace_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseSimulation_0
{
	class U_SolarisSignatureFunctionOuter;
	class USimulation;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Many_R;
}

namespace EpicGamesTemporary_0
{
	struct Ftuple_Lrotation_Mrotation_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace Player_SkyDiveAndGlide_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace VerseGameplayTags_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Player_Land_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Entity_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace SwimmingAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Gameplay_FaceSystem_StateMachine_AnimBP
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Player_ProceduralLayering_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseDevices_0
{
	struct Ftuple_Lvector3_Mrotation_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lcreative__object_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace EpicGamesEngine_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Verse
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lint_Many_R;
	struct Ftuple_Lint_Mint_Mint_R;
	struct Ftuple_Lint_Mint_R;
}

namespace ExecutionTestSuite_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltuple_L_R_Tvoid_M_QInterval_Nfloat_20_3d_20_2e_2e_2e_R;
}

namespace Player_ZipLine_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace VerseRestricted
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Component_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePrint
{
	class U_Root;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
}

namespace EpicGamesEngineRestricted_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mlogic_R;
}

namespace EpicGamesAssets_0
{
	class U_SolarisSignatureFunctionOuter;
	class UAssets;
	struct Ftuple_L_R;
}

namespace UnrealEngineExperimental_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
}

namespace VerseExperimental
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Mint_R;
}

namespace VerseQuery_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFortnite_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lgame__action__instigator_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lguard__alert__level_Mdamage__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Mhearing__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Msight__perception__settings_R;
	struct Ftuple_Lguard__alert__level_Mtouch__perception__settings_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltarget__info_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace VerseAIBase_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lany_M_Kchar_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__inventory__item__asset_Mint_R;
}

namespace VerseFortniteInternal_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Mint_R;
}

namespace VerseFortniteUI_0
{
	class U_SolarisSignatureFunctionOuter;
	class UUI;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_R;
}

namespace Player_FreeFlying_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_BuildingPose_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_SourcePose_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Sprint_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_Goop_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_FirstPersonAdditives_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_LocomotionAdditives_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace MANG_PatrolLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace Player_FullBodyAimOffsets_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace WolfRidingPlayerLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ItemizationVerse_0
{
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_R;
	struct Ftuple_Lcreative__object_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
}

namespace JackalVehicleLayerAnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace B_AnimBP_HightowerRadish
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace Fortnite_Base_3L_Head_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace F_MED_VoidRedemption_Rebel_AnimBP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
